auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki

storage_config:
  filesystem:
    chunks_directory: /loki/chunks
    rules_directory: /loki/rules

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  retention_enabled: true

limits_config:
  retention_period: 168h
  reject_old_samples: true
  reject_old_samples_max_age: 168h