---
- name: Restart Jira container (docker compose)
  hosts: "{{ target | default('vm_jira') }}"
  become: true
  vars:
    jira_compose_file: "/opt/jira/compose.yml"
    jira_service_name: "jira"
    jira_http_port: 8080
  tasks:
    - name: Restart jira service via docker compose
      ansible.builtin.command:
        cmd: docker compose -f {{ jira_compose_file }} restart {{ jira_service_name }}
      register: restart_out
      changed_when: true
      failed_when: false

    - name: Ensure jira is up (when it wasn't running)
      ansible.builtin.command:
        cmd: docker compose -f {{ jira_compose_file }} up -d {{ jira_service_name }}
      when: restart_out.rc != 0
      changed_when: true

    - name: Wait for Jira HTTP port
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: "{{ jira_http_port }}"
        delay: 3
        timeout: 600